services:
  - type: web
    name: electric-ai-analyzer
    env: python
    buildCommand: apt-get update && apt-get install -y tesseract-ocr && pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 180 --workers 1 --threads 1 --access-logfile - --error-logfile - --capture-output
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DATABASE_NAME
        value: electric_ai
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9
